# Generated by Django 5.1.5 on 2025-01-20 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_name", models.CharField(max_length=50, unique=True)),
                ("dep_code", models.CharField(max_length=10, unique=True)),
                (
                    "dep_isactive",
                    models.CharField(
                        choices=[("Y", "ACTIVE"), ("N", "INACTIVE")], max_length=1
                    ),
                ),
                ("dep_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dep_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_fname", models.CharField(max_length=100)),
                ("emp_lname", models.CharField(max_length=100)),
                ("emp_fullname", models.CharField(max_length=100)),
                ("emp_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "emp_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "emp_isactive",
                    models.CharField(
                        choices=[("Y", "ACTIVE"), ("N", "INACTIVE")], max_length=1
                    ),
                ),
                (
                    "emp_added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emp_department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization1.department",
                    ),
                ),
            ],
        ),
    ]
