# Generated by Django 5.1.5 on 2025-01-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization1', '0002_alter_employee_emp_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50, unique=True)),
                ('dep_code', models.CharField(max_length=10, unique=True)),
                ('dep_isactive', models.CharField(choices=[('Y', 'ACTIVE'), ('N', 'INACTIVE')], max_length=1)),
                ('dep_created_at', models.DateTimeField(auto_now_add=True)),
                ('dep_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
